name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Set rust to nightly
        run: rustup override set nightly
      - name: Install components
        run: rustup component add rustfmt clippy
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        run: cargo test --verbose --release

  test-min-supported:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run min-supported
        working-directory: fixtures/min-supported
        run: cargo run --release

  test-max-tested:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run max-tested
        working-directory: fixtures/max-tested
        run: cargo run --release

  test-profiling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set rust to nightly
        run: rustup override set nightly
      - name: Run profiling script
        run: ./scripts/profiling.rs

  test-timings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set rust to nightly
        run: rustup override set nightly
      - name: Run timings script
        run: ./scripts/timings.rs 1234 "Hello world"

  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run simple_usage
        run: cargo run --example simple_usage
      - name: Run single_threaded
        run: cargo run --example single_threaded
      - name: Run custom_tuner
        run: cargo run --example custom_tuner
